### ISSUE TITLE
不会用

### ISSUE THREAD

**Issue by Layczm** [zeffon/vue-package#1]
作为一个小白，确实用不起来， 可以出个较详细的使用文档么？

**Comment by zeffon** [comment]
你可以参考该项目 https://github.com/Zeffon/vue-auto-logout

**Comment by zeffon** [comment]
目前比较忙了，后面回出一个详细教程

**Comment by Layczm** [comment]
代码运行报错。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zeffon/vue-package"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 上午10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zeffon/vue-package] 不会用 (#1)





 
你可以参考该项目 https://github.com/Zeffon/vue-auto-logout
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zeffon** [comment]
是vue-auto-logout项目运行报错吗？

**Comment by Layczm** [comment]
是的
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zeffon/vue-package"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zeffon/vue-package] 不会用 (#1)





 
是vue-auto-logout项目运行报错吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zeffon** [comment]
能否提供具体的报错信息？

**Comment by Layczm** [comment]
不是有发一张图片过去了么?&nbsp; &nbsp;就单纯的拉代码，然后yarn&nbsp; 然后再执行，yarn dev&nbsp; &nbsp;没有多余操作 。 。 。 。&nbsp;

**Comment by Layczm** [comment]
ERROR in ./example/src/App.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):
[vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.


ERROR in ./example/src/App.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):
vue-loader was used without the corresponding plugin. Make sure to include VueLoaderPlugin in your webpack config.


ERROR in ./example/src/App.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
&nbsp; &nbsp; at parse ***@***.***\component-compiler-utils\dist\parse.js:15:23)
&nbsp; &nbsp; at Object.module.exports (E:\npmPackage\vue-auto-logout\node_modules\vue-loader\lib\index.js:67:22)
i ｢wdm｣: Failed to compile.&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 你说的是这个？&nbsp; 还是？&nbsp;&nbsp;

**Comment by zeffon** [comment]
这边并没有收到图片，看报错是否是因为包不兼容的问题。现在更新了代码，你可以pull代码后重新试一下。

**Comment by zeffon** [comment]
操作步骤如下：

1. pull代码
2. 删除node
3. 重新安装依赖 yarn install
4. 运行项目 yarn dev

**Comment by Layczm** [comment]
还是一样报错呀 。 。 。 。
PS E:\npmPackage\vue-auto-logout&gt; yarn dev
yarn run v1.22.10
$ webpack-dev-server --config example/webpack.config.js --host 127.0.0.1
i ｢wds｣: Project is running at http://127.0.0.1:8080/
i ｢wds｣: webpack output is served from /dist/
i ｢wds｣: Content not from webpack is served from E:\npmPackage\vue-auto-logout\example
× ｢wdm｣:&nbsp; &nbsp; 46 modules


ERROR in ./example/src/App.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):
[vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.


ERROR in ./example/src/App.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):
vue-loader was used without the corresponding plugin. Make sure to include VueLoaderPlugin in your webpack config.


ERROR in ./example/src/App.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
&nbsp; &nbsp; at parse ***@***.***\component-compiler-utils\dist\parse.js:15:23)
&nbsp; &nbsp; at Object.module.exports (E:\npmPackage\vue-auto-logout\node_modules\vue-loader\lib\index.js:67:22)
i ｢wdm｣: Failed to compile.

**Comment by Layczm** [comment]
你本地可以运行使用？ 如果你没事， 你可以试一下看看&nbsp;

**Comment by zeffon** [comment]
这就是vue-template-compiler不兼容问题，现在已经这个依赖去掉了。先更新代码，然后确保node_modules删除后，再yarn install，最后执行yarn dev。

**Comment by zeffon** [comment]
我这边是正常的，之前也是报错vue-template-compiler不兼容问题，忘记去掉该依赖，所以导致该问题。（vue3不需要再引入vue-template-compiler）
